services:
  - type: web
    name: cvsite
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python cvsite/manage.py collectstatic --no-input
    startCommand: cd cvsite && gunicorn cvsite.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: cvsite.settings
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"