services:
  - type: web
    name: cvsite
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn cvsite.cvsite.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 